### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by deadbeathorse** [ancalentari/twitch-stream-recorder#23]
This script works on my laptop, but my laptop is prone to shutting down randomly throughout the day. After installing it on my desktop computer yesterday, I consistently run into this error upon running the script:

PS C:\Users\DBH> py twitch-recorder.py -u a_seagull
checking for a_seagull every 15 seconds, recording with best quality
a_seagull online, stream recording in session
Traceback (most recent call last):
  File "twitch-recorder.py", line 199, in <module>
    main(sys.argv[1:])
  File "twitch-recorder.py", line 195, in main
    twitch_recorder.run()
  File "twitch-recorder.py", line 82, in run
    self.loop_check(recorded_path, processed_path)
  File "twitch-recorder.py", line 152, in loop_check
    subprocess.call(
  File "C:\Program Files\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
PS C:\Users\DBH

**Comment by hunkyburrito** [comment]
Make sure you have streamlink installed and on your system path
