### ISSUE TITLE
fail start

### ISSUE THREAD

**Issue by Baltimora** [ancalentari/twitch-stream-recorder#3]
log after "python twitch-recorder.py"

```
Traceback (most recent call last):
  File "twitch-recorder.py", line 199, in <module>
    main(sys.argv[1:])
  File "twitch-recorder.py", line 167, in main
    twitch_recorder = TwitchRecorder()
  File "twitch-recorder.py", line 42, in __init__
    self.access_token = self.fetch_access_token()
  File "twitch-recorder.py", line 46, in fetch_access_token
    token_response.raise_for_status()
  File "C:\Users\dmitr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://id.twitch.tv/oauth2/token?client_id=jzkbprff40iqj646a697cyrvl0zt2m6&client_secret=hi1moptnyhyd0h4sxmhtsx7gy905vr&grant_type=client_credentials
```

**Comment by ancalentari** [comment]
HTTP 403 means access denied, so you have wrong credentials. Configure correct client id and client secret. Read the instructions again if necessary.
