### ISSUE TITLE
Script No Longer Working

### ISSUE THREAD

**Issue by ConnerGinn** [ancalentari/twitch-stream-recorder#6]
I was able to get this script working a day or two ago. I tested it and it worked splendidly.

Today I went to run the script and I am consistently receiving the following errors.

`checking for <streamername> every 15 seconds, recording with best quality`
`<streamername> online, stream recording in session`
`Traceback (most recent call last):`
`  File "D:\twitch-recorder.py", line 199, in <module>`
`    main(sys.argv[1:])`
`  File "D:\twitch-recorder.py", line 195, in main`
`    twitch_recorder.run()`
`  File "D:\twitch-recorder.py", line 82, in run`
`    self.loop_check(recorded_path, processed_path)`
`  File "D:\twitch-recorder.py", line 152, in loop_check`
`    subprocess.call(`
`  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call`
`    with Popen(*popenargs, **kwargs) as p:`
`  File "C:\Users\USERj\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__`
`    self._execute_child(args, executable, preexec_fn, close_fds,`
`  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child`
`    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,`
`FileNotFoundError: [WinError 2] The system cannot find the file specified`

Any help would be massively appreciated.

**Comment by ConnerGinn** [comment]
Script is suddenly now working again, after changing nothing. *shrugs*
